---
# defaults file for wordpress
wordpress_packages:
  - httpd
  - mysql
  - python-pip
  - gcc
  - mysql-devel
  - php
  - php-mysqlnd
  - php-mbstring
wordpress_database_host: 'terraform-20221215220608177800000001.cz9lujtdwkpp.us-east-1.rds.amazonaws.com' #replace with RDS endpoint
wordpress_database: 'wordpress'
wordpress_user: 'admin'
wordpress_password: 'adminadmin'
wordpress_configuration: '/var/www/html/wp-config.php'
